set shell := ["bash", "-cu"]

lint:
	@command -v shellcheck >/dev/null 2>&1 || { echo 'shellcheck not installed'; exit 1; }
	shellcheck lib/*.sh

test:
	@command -v bats >/dev/null 2>&1 || { echo 'bats not installed'; exit 1; }
	bats tests

build:
  #!/usr/bin/env bash
  set -euo pipefail

  ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  DIST="$ROOT/dist/install-lib.sh"
  MODULES=(
    lib/install-lib.sh
    lib/logging.sh
    lib/ui.sh
    lib/os.sh
    lib/packages.sh
  )

  mkdir -p "$(dirname "$DIST")"
  cat <<'HEADER' >"$DIST"
  #!/usr/bin/env bash
  # shellcheck shell=bash
  #
  # Auto-generated by scripts/build.sh. Do not edit directly.
  HEADER

  for module in "${MODULES[@]}"; do
    {
      echo
      echo "# --- ${module} ---"
      cat "$ROOT/$module"
    } >>"$DIST"
  done

  cat <<'FOOTER' >>"$DIST"
  # --- End of install-lib ---
  #
  # vim: set ft=bash:
  FOOTER

  chmod +x "$DIST"
  printf 'Generated %s\n' "$DIST"

# vim: set ft=just:
