set shell := ["bash", "-cu"]

lint:
	@command -v shellcheck >/dev/null 2>&1 || { echo 'shellcheck not installed'; exit 1; }
	shellcheck lib/*.sh

test:
	@command -v bats >/dev/null 2>&1 || { echo 'bats not installed'; exit 1; }
	bats tests

build:
  #!/usr/bin/env bash
  set -euo pipefail

  ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  DIST="$ROOT/dist/install-lib.sh"
  MODULES=(
    lib/install-lib.sh
    lib/logging.sh
    lib/ui.sh
    lib/os.sh
    lib/packages.sh
  )

  mkdir -p "$(dirname "$DIST")"
  /bin/cat <<'HEADER' >"$DIST"
  #!/usr/bin/env bash
  # shellcheck shell=bash
  #
  # Auto-generated by scripts/build.sh. Do not edit directly.
  # --- Start of install-lib ---
  if [[ -n "${INSTALL_LIB_OS_LOADED:-}" ]]; then
    return 0
  fi
  declare -g INSTALL_LIB_OS_LOADED=1
  HEADER

  for module in "${MODULES[@]}"; do
    {
      echo
      echo "# --- ${module} ---"
      /bin/cat "$ROOT/$module" | \
        grep -Ev '^\s*#\s*(shellcheck\s*shell=|!/usr/bin/env\s*bash|vim:\s*set\s*ft=bash:)' | \
        awk '/^[[:space:]]*if[[:space:]]*\[\[[[:space:]]*-n[[:space:]]*"\${INSTALL_LIB_OS_LOADED:-}"[[:space:]]*\]\];[[:space:]]*then[[:space:]]*$/ {skip=1; next}
          /^[[:space:]]*declare[[:space:]]+-g[[:space:]]+INSTALL_LIB_OS_LOADED=1[[:space:]]*$/ {skip=0; next}
          skip { next }
          { print }' | \
        sed '/^[[:space:]]*$/d'
    } >>"$DIST"
  done

  /bin/cat <<'FOOTER' >>"$DIST"
  # --- End of install-lib ---
  #
  # vim: set ft=bash:
  FOOTER

  chmod +x "$DIST"
  printf 'Generated %s\n' "$DIST"

# vim: set ft=just:
