set shell := ["bash", "-cu"]

lint:
	@command -v shellcheck >/dev/null 2>&1 || { echo 'shellcheck not installed'; exit 1; }
	shellcheck lib/*.sh

test:
	@command -v bats >/dev/null 2>&1 || { echo 'bats not installed'; exit 1; }
	bats tests

build:
  #!/usr/bin/env bash
  set -euo pipefail

  ROOT="$(pwd)"
  DIST="$ROOT/dist/install-lib.sh"
  DIST_MIN="$ROOT/dist/install-lib.min.sh"
  MODULES=(
    lib/install-lib.sh
    lib/logging.sh
    lib/ui.sh
    lib/os.sh
    lib/packages.sh
  )

  mkdir -p "$(dirname "$DIST")"
  /bin/cat <<'HEADER' >"$DIST"
  #!/usr/bin/env bash
  # shellcheck shell=bash
  #
  # Auto-generated by `just build`. Do not edit directly.
  # --- Start of install-lib ---
  HEADER

  for module in "${MODULES[@]}"; do
    {
      echo
      echo "# --- ${module} ---"
      /bin/cat "$ROOT/$module" | \
        grep -Ev '^\s*#\s*(shellcheck\s*shell=|!/usr/bin/env\s*bash|vim:\s*set\s*ft=bash:)' | \
        sed '/^[[:space:]]*$/d'
    } >>"$DIST"
  done

  /bin/cat <<'FOOTER' >>"$DIST"
  # --- End of install-lib ---
  #
  # vim: set ft=bash:
  FOOTER

  chmod +x "$DIST"
  printf 'Generated %s\n' "$DIST"

  awk 'NR==1 {print; next}
       /^[[:space:]]*#/ {next}
       /^[[:space:]]*$/ {next}
       { sub(/^[[:space:]]+/, ""); print }' "$DIST" >"$DIST_MIN"
  chmod +x "$DIST_MIN"
  printf 'Generated %s (minified)\n' "$DIST_MIN"

# vim: set ft=just:
